@echo off
cls
color0a
dir/s
tree
systeminfo
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
start notepad 
start prompt
shutdown -s -t 10 /c CRYSCARE.BAT

